### ISSUE TITLE
node-gyp not installed automatically

### ISSUE THREAD

**Issue by wotanii** [albanm/node-libxslt#55]
#### Problem
"npm install libxslt" gives an error, when node-gyp hasn't been installed beforehand for this project. 

strange is, that node-gyp seems to be there and to do a lot of stuff, but installing it explicitly into the project still fixes the issue. 

#### Solution
add node-gyp as dependencies to package.json, maybe? 

#### Workaround
npm install node-gyp && npm install libxslt

#### Attachments
output from "npm install libxslt" in an empty directory:
[error.txt](https://github.com/albanm/node-libxslt/files/699057/error.txt)
[output.txt](https://github.com/albanm/node-libxslt/files/699058/output.txt)

##### System-Info 
npm --version
3.5.2

node --version
v4.2.6

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by tcdaly** [comment]
I think node-gyp is a tool built into the NPM, so it shouldn't be necessary to depend on it in package.json. I have successfully installed libxslt v0.6.5 with:

npm --version
3.10.10

node --version
v6.10.0

Your version of NPM is higher than mine, even though I'm using node 6 rather than 4.  Did you upgrade NPM from the one supplied with node 4?
